osx_image: xcode11.5
sudo: required
language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install xcpretty
script: rake test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5
