name: Test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        workspace: Demo/ScrollingNavbarDemo.xcworkspace
        scheme: ScrollingNavbarDemo
        destination: platform=iOS
        action: test
